### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by JohnUrban** [ganlab/GALA#25]
Hi,

Thanks for the cool program. I am giving it a try.

First thing that pops up is this error:
```
Traceback (most recent call last):
  File "/central/groups/carnegie_poc/jurban/software/gala/GALA/gala", line 19, in <module>
    from read_extract import read_extract
  File "/central/groups/carnegie_poc/jurban/software/gala/GALA/src/read_extract.py", line 23
    if read_file[-2:]=='gz':
                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

I am guessing Python didn't complain in the past about this, but now it is, which is annoying.

I fixed it with:
```
cp read_extract.py save_original_read_extract.py
awk '{gsub("\t","    "); print}' save_original_read_extract.py > read_extract.py
```

I will report back if other files start reporting the same error.

As an aside, the dependencies on the Github front page of this Repo says it depends on Python 2.7, yet that file calls for python 3. Can you update the list of dependencies?

Many thanks!

Best,

John Urban

**Comment by aabaricalla** [comment]
same problem here, not python2.7 nor python3.11 work with this.
Hope there is a quick solution
