### ISSUE TITLE
Can it be installed through Conda

### ISSUE THREAD

**Issue by ZKYthli** [ganlab/GALA#33]
This software has many dependencies, can it be installed through Conda?

**Comment by jancely** [comment]
When install, error like this:
Traceback (most recent call last):
  File "/usr/bin/gala", line 19, in <module>
    from        read_extract import read_extract
  File "/usr/bin/read_extract.py", line 23
    if read_file[-2:]=='gz':
TabError: inconsistent use of tabs and spaces in indentation

**Comment by nponts** [comment]
Same as you, I would like to give it a shot but cannot get it to work - I don't know what python to use, not sure about all the dependencies, I'm stuck!Please help!
